### ISSUE TITLE
Compile Error when running with DirectX Backend

### ISSUE THREAD

**Issue by iMplode-nZ** [LuisaGroup/luisa-compute-rs#5]
The commands I did were to clone the repository, and then do

```
cargo r --release --example raytracing -- dx
```
(I also tried it with the path_tracer example)

The error is:

```
[2023-09-16T12:05:25Z ERROR lc-cpp] Compile Error: hlsl.hlsl:793:15: error: invalid format for vector swizzle 'v'
    l84.v2=l83.v2.v[0u];
                  ^
    hlsl.hlsl:794:15: error: invalid format for vector swizzle 'v'
    l84.v3=l83.v2.v[1u];
```

I tried running the callable example with the dx backend and it seems to work.

My computer is a windows 10 install with DirectX 12, with a 3080 (laptop) gpu.

**Comment by shiinamiyuki** [comment]
I have pushed a fix

**Comment by iMplode-nZ** [comment]
Alright, thanks!
